name: Build on push with tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Install NSIS
        shell: powershell
        run: choco install nsis -y
      - name: Build
        run: |
          rake build

      - name: Compute version
        id: version
        run: rake action:version

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.version.outputs.prerelease }}
          body: ${{ steps.version.outputs.body }}
          files: |
            ./build/*.*
